language: elixir

elixir:
  - 1.6

otp_release:
  - 20.3

env:
  global:
    - MIX_ENV=test

notifications:
  email: false

sudo: false

script:
  - mix format --check-formatted
  - mix compile --force --warnings-as-errors
  - mix test
